name: bozletrando.api

services:
  api:
    image: agenciaboz/bozletrando.api
    container_name: bozletrando.api
    environment:
      - PORT=8089
    ports:
      - "8089:8089"
    network_mode: "host"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    volumes:
      - static_volume:/app/static

volumes:
  static_volume:
    name: "bozletrando.api"